name: Titan-Processing
channels:
  - conda-forge
  - https://repo.prefix.dev/titan-forge
  - nodefaults
dependencies:
  - opencv-titan
  - nlohmann_json
  - cmake
  - ninja
  - clang
  - clangxx
  - googletest
